### ISSUE TITLE
"Official" repo

### ISSUE THREAD

**Issue by zlorf** [sciyoshi/django-dbsettings#13]
Hi,

Would you be so nice to change the readme and point out that your repository is no longer maintained and give a link to my fork (https://github.com/zlorf/django-dbsettings)?  I've been already writing code and publishing releases to PyPI since 06/2012.

Thanks a lot for the initial dbsettings work!

**Comment by andybak** [comment]
I just wasted a bunch of time as I was using the pip version whilst reading the code/docs from this repo.

Would it not be best to delete this repo and redirect to zlorf's?

**Comment by andybak** [comment]
Talk about poor memory! I forgot about this discussion: https://github.com/zlorf/django-dbsettings/issues/16

Anyway - I'm proof incarnate that things are still confusing. This repo has slipped behind again zlorf's again. It would be good for the community to have single canonical repo - and the one in PyPi preferably should be the same one that comes top in Google which it currently isn't.

**Comment by sciyoshi** [comment]
I've added a note about the @zlorf's fork being the official PyPi version. Note that he has had commit access to this repo, and @andybak I've just added you as well. Although I'm not actively maintaining this anymore, I agree that it'd be best to have a single repo. If there's a Django-affiliated project willing to take ownership of this, I'd happily transfer it there.
