### ISSUE TITLE
Django 1.10 compatibility?

### ISSUE THREAD

**Issue by manikos** [sciyoshi/django-dbsettings#16]
Yesterday I run `python manage.py test` on my project (after I upgraded it to Django 1.10) to run the whole Django test suite. It fails on django-dbsettings at file `management.py` line 14 (`defaults={'name': appname}`).
The error thrown by Django is at file `django/db/models/base.py` line 555 where it states: `TypeError: 'name' is an invalid keyword argument for this function`.
Should `django-dbsettings` be upgraded to fit current trends or just leave it as an error?

**Comment by zlorf** [comment]
Of course it should be fixed; thank you for reporting.

**Comment by zlorf** [comment]
Uploaded 0.10 to PyPI

**Comment by manikos** [comment]
That worked brilliantly! Thank you very much!
