### ISSUE TITLE
App doesn't compatible with Django 1.5

### ISSUE THREAD

**Issue by Deadly0** [sciyoshi/django-dbsettings#7]
Error message: TemplateSyntaxError: 'adminmedia' is not a valid tag library: Template library adminmedia not found.

Django 1.5 deprecation log: 
The template tags library adminmedia and the template tag {% admin_media_prefix %} will be removed in favor of the generic static files handling. (This is faster than the usual deprecation path; see the Django 1.4 release notes.)

https://docs.djangoproject.com/en/dev/internals/deprecation/#id2

**Comment by sciyoshi** [comment]
This should now work in 0.8.1 thanks to @zlorf's work to make this compatible.
